version: 2.1

setup: true

executors:
  base:
    docker:
      - image: cimg/base:current
        user: root

jobs:
  random:
    executor: base
    steps:
      - run:
          echo << pipeline.parameters >>

workflows:
  main:
    jobs:
      - random
